<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
>The input layer is the input to the neural network. It is the data being fed in. Sometimes the input layer is backfed. 

### Hidden Layer:
>The hidden layer is the "black box" of Neural Networks. This is where the weights and responses for data to be established. 

### Output Layer:
>This is the neural network parallel to the model prediction in a classic linear or logistic regression. 

### Neuron:
>Neurons or "nodes" recieve input and pass a signal on if a certain condition or threshold is met. 

### Weight:
>Weights are the preference trained into a node based on the input. Data with greater association with better predictions is given a higher weight.

### Activation Function:
>The biology inspired portion of the Neural Network. Each node in a given layer typically has the same activation function. This activation function determines whether or not a particular node is fired. In Artificial Neural Networks activation functions decide how much signal to pass onto the next layer. This is why they are sometimes referred to as transfer functions because they determine how much signal is transferred to the next layer.

### Node Map:
>Node map refers to the general architecture of a neural network. It determines what types of nodes and the order of layers occur in a given model. 

### Perceptron:
>Once of the most simple neural networks, a perceptron is just a single node or neuron of a neural network with nothing else. It can take any number of inputs and spit out an output. What a neuron does is it takes each of the input values, multplies each of them by a weight, sums all of these products up, and then passes the sum through what is called an "activation function" the result of which is the final value.


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

When data is input into the neural network, it enters through the input nodes. The information then enters the the hidden layer. The hidden layers apply specific weights and biases to the information and if the resulting value is meets a threshold determined by the activation function, it passes on to either another hidden layer or an output layer. The output layer provides the desired result, often a prediciton or generation of some kind. 

## Write your own perceptron code that can correctly classify a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [202]:
import numpy as np

# Establish Inputs
inputs = np.array([
    [0,0,1],
    [1,0,1],
    [0,1,1],
    [1,1,1]
])

# Establish Target 
target = [[1], 
          [1], 
          [1], 
          [0]]

# Sigmoid functions
def sigmoid(x):
    return 1 / (1+np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx* (1-sx)
    

In [203]:
print('input:','\n',inputs.shape,'\n')

# Establish random weights for each input
weights = np.random.random((3,1)) - 1
print('weights:','\n', weights,'\n')

# Weighted Sum of Input and Weights
weighted_sum = np.dot(inputs, weights)
print('weighted sums:','\n', weighted_sum,'\n')

# Apply the sigmoid activatin function
activated_output = sigmoid(weighted_sum)
print('activation function output:','\n',activated_output,'\n')

# Correct with the error
error = target - activated_output
print('errors:','\n', error, '\n')

adjustments = error * sigmoid_derivative(activated_output)
print('backpropagation adjustments:','\n',adjustments,'\n')

weights += np.dot(inputs.T, adjustments)
print('backprop weights','\n',weights,'\n')

input: 
 (4, 3) 

weights: 
 [[-0.02964715]
 [-0.16796537]
 [-0.17563552]] 

weighted sums: 
 [[-0.17563552]
 [-0.20528267]
 [-0.34360089]
 [-0.37324804]] 

activation function output: 
 [[0.45620365]
 [0.4488588 ]
 [0.41493504]
 [0.40775642]] 

errors: 
 [[ 0.54379635]
 [ 0.5511412 ]
 [ 0.58506496]
 [-0.40775642]] 

backpropagation adjustments: 
 [[ 0.12911391]
 [ 0.13107181]
 [ 0.14014688]
 [-0.09781658]] 

backprop weights 
 [[ 0.00360808]
 [-0.12563507]
 [ 0.12688051]] 



In [146]:
weights = np.random.random((3,1)) - 1

for iteration in range(10000):
    
    # Weighted Sum of inputs/weights
    
    weighted_sum = np.dot(inputs, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Calculate the Error
    error = target - activated_output
    
    # Adjustments
    adjustments = error * sigmoid_derivative(activated_output)
    
    # New weights. 
    weights += np.dot(inputs.T, adjustments)
    
print('Weights after Training')
print(weights)

print('Outputs after training')
print(activated_output)

Weights after Training
[[-11.84087442]
 [-11.84087442]
 [ 17.81017581]]
Outputs after training
[[0.99999998]
 [0.99745024]
 [0.99745024]
 [0.0028108 ]]


## Implement your own Perceptron Class and use it to classify a binary dataset like: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 
- [Titanic](https://raw.githubusercontent.com/ryanleeallred/datasets/master/titanic.csv)
- [A two-class version of the Iris dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/Iris.csv)

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [148]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')

In [256]:
print('shape: ', df.shape,'\n')
df['bias'] = np.ones(768)
df.head()

shape:  (768, 10) 



Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  bias  
0                     0.627   50        1   1.0  
1                     0.351   31        0   1.0  
2                     0.672   32        1   1.0  
3                     0.167   21        0   1.0  
4                     2.288   33        1   1.0

In [257]:
inputs = df.drop(columns = 'Outcome')

target = df[['Outcome']].values

In [258]:
weights = np.random.random((inputs.shape[1],1)) - 1

for iteration in range(10000):
    
    # Weighted Sum of inputs/weights
    
    weighted_sum = np.dot(inputs, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Calculate the Error
    error = target - activated_output
    
    # Adjustments
    adjustments = error * sigmoid_derivative(activated_output)
    
    # New weights. 
    weights += np.dot(inputs.T, adjustments)

prediction = activated_output

prediction.shape

(768, 1)

In [259]:
prediction.sum()

645.0

In [260]:
df['Outcome'].sum()

268

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?